// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EstateReporting.IntegrationTests.Reporting
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "base")]
    [Xunit.TraitAttribute("Category", "shared")]
    public partial class TransactionsByWeekReportsFeature : object, Xunit.IClassFixture<TransactionsByWeekReportsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "base",
                "shared"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TransactionsByWeekReports.feature"
#line hidden
        
        public TransactionsByWeekReportsFeature(TransactionsByWeekReportsFeature.FixtureData fixtureData, EstateReporting_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Reporting", "TransactionsByWeekReports", null, ProgrammingLanguage.CSharp, new string[] {
                        "base",
                        "shared"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                        "ResourceName",
                        "DisplayName",
                        "Secret",
                        "Scopes",
                        "UserClaims"});
            table45.AddRow(new string[] {
                        "estateManagement",
                        "Estate Managememt REST",
                        "Secret1",
                        "estateManagement",
                        "MerchantId, EstateId, role"});
            table45.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST",
                        "Secret1",
                        "transactionProcessor",
                        ""});
#line 6
 testRunner.Given("the following api resources exist", ((string)(null)), table45, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                        "ClientId",
                        "ClientName",
                        "Secret",
                        "AllowedScopes",
                        "AllowedGrantTypes"});
            table46.AddRow(new string[] {
                        "serviceClient",
                        "Service Client",
                        "Secret1",
                        "estateManagement,transactionProcessor",
                        "client_credentials"});
#line 11
 testRunner.Given("the following clients exist", ((string)(null)), table46, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table47 = new TechTalk.SpecFlow.Table(new string[] {
                        "ClientId"});
            table47.AddRow(new string[] {
                        "serviceClient"});
#line 15
 testRunner.Given("I have a token to access the estate management and transaction processor resource" +
                    "s", ((string)(null)), table47, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table48 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName"});
            table48.AddRow(new string[] {
                        "Test Estate 1"});
            table48.AddRow(new string[] {
                        "Test Estate 2"});
#line 19
 testRunner.Given("I have created the following estates", ((string)(null)), table48, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table49 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "RequireCustomMerchantNumber",
                        "RequireCustomTerminalNumber"});
            table49.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "True",
                        "True"});
            table49.AddRow(new string[] {
                        "Test Estate 2",
                        "Safaricom",
                        "True",
                        "True"});
#line 24
 testRunner.Given("I have created the following operators", ((string)(null)), table49, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table50 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription"});
            table50.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract"});
            table50.AddRow(new string[] {
                        "Test Estate 2",
                        "Safaricom",
                        "Safaricom Contract"});
#line 29
 testRunner.Given("I create a contract with the following values", ((string)(null)), table50, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table51 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription",
                        "ProductName",
                        "DisplayText",
                        "Value"});
            table51.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Custom",
                        ""});
            table51.AddRow(new string[] {
                        "Test Estate 2",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Custom",
                        ""});
#line 34
 testRunner.When("I create the following Products", ((string)(null)), table51, "When ");
#line hidden
            TechTalk.SpecFlow.Table table52 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription",
                        "ProductName",
                        "CalculationType",
                        "FeeDescription",
                        "Value"});
            table52.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Fixed",
                        "Merchant Commission",
                        "2.50"});
            table52.AddRow(new string[] {
                        "Test Estate 2",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Percentage",
                        "Merchant Commission",
                        "0.85"});
#line 39
 testRunner.When("I add the following Transaction Fees", ((string)(null)), table52, "When ");
#line hidden
            TechTalk.SpecFlow.Table table53 = new TechTalk.SpecFlow.Table(new string[] {
                        "MerchantName",
                        "AddressLine1",
                        "Town",
                        "Region",
                        "Country",
                        "ContactName",
                        "EmailAddress",
                        "EstateName"});
            table53.AddRow(new string[] {
                        "Test Merchant 1",
                        "Address Line 1",
                        "TestTown",
                        "Test Region",
                        "United Kingdom",
                        "Test Contact 1",
                        "testcontact1@merchant1.co.uk",
                        "Test Estate 1"});
            table53.AddRow(new string[] {
                        "Test Merchant 2",
                        "Address Line 1",
                        "TestTown",
                        "Test Region",
                        "United Kingdom",
                        "Test Contact 2",
                        "testcontact2@merchant2.co.uk",
                        "Test Estate 1"});
            table53.AddRow(new string[] {
                        "Test Merchant 3",
                        "Address Line 1",
                        "TestTown",
                        "Test Region",
                        "United Kingdom",
                        "Test Contact 3",
                        "testcontact3@merchant2.co.uk",
                        "Test Estate 2"});
#line 44
 testRunner.Given("I create the following merchants", ((string)(null)), table53, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table54 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperatorName",
                        "MerchantName",
                        "MerchantNumber",
                        "TerminalNumber",
                        "EstateName"});
            table54.AddRow(new string[] {
                        "Safaricom",
                        "Test Merchant 1",
                        "00000001",
                        "10000001",
                        "Test Estate 1"});
            table54.AddRow(new string[] {
                        "Safaricom",
                        "Test Merchant 2",
                        "00000002",
                        "10000002",
                        "Test Estate 1"});
            table54.AddRow(new string[] {
                        "Safaricom",
                        "Test Merchant 3",
                        "00000003",
                        "10000003",
                        "Test Estate 2"});
#line 50
 testRunner.Given("I have assigned the following  operator to the merchants", ((string)(null)), table54, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table55 = new TechTalk.SpecFlow.Table(new string[] {
                        "DeviceIdentifier",
                        "MerchantName",
                        "EstateName"});
            table55.AddRow(new string[] {
                        "123456780",
                        "Test Merchant 1",
                        "Test Estate 1"});
            table55.AddRow(new string[] {
                        "123456781",
                        "Test Merchant 2",
                        "Test Estate 1"});
            table55.AddRow(new string[] {
                        "123456782",
                        "Test Merchant 3",
                        "Test Estate 2"});
#line 56
 testRunner.Given("I have assigned the following devices to the merchants", ((string)(null)), table55, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table56 = new TechTalk.SpecFlow.Table(new string[] {
                        "Reference",
                        "Amount",
                        "DateTime",
                        "MerchantName",
                        "EstateName"});
            table56.AddRow(new string[] {
                        "Deposit1",
                        "30000.00",
                        "Today",
                        "Test Merchant 1",
                        "Test Estate 1"});
            table56.AddRow(new string[] {
                        "Deposit1",
                        "10000.00",
                        "Today",
                        "Test Merchant 2",
                        "Test Estate 1"});
            table56.AddRow(new string[] {
                        "Deposit1",
                        "10000.00",
                        "Today",
                        "Test Merchant 3",
                        "Test Estate 2"});
#line 62
 testRunner.Given("I make the following manual merchant deposits", ((string)(null)), table56, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Sales Transactions By Week - Transactions All On Same Day")]
        [Xunit.TraitAttribute("FeatureTitle", "TransactionsByWeekReports")]
        [Xunit.TraitAttribute("Description", "Sales Transactions By Week - Transactions All On Same Day")]
        public virtual void SalesTransactionsByWeek_TransactionsAllOnSameDay()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sales Transactions By Week - Transactions All On Same Day", null, tagsOfScenario, argumentsOfScenario);
#line 68
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 70
 testRunner.Given("I set the date for today to \"15/10/2020\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table57 = new TechTalk.SpecFlow.Table(new string[] {
                            "DateTime",
                            "TransactionNumber",
                            "TransactionType",
                            "MerchantName",
                            "DeviceIdentifier",
                            "EstateName",
                            "OperatorName",
                            "TransactionAmount",
                            "CustomerAccountNumber",
                            "CustomerEmailAddress",
                            "ContractDescription",
                            "ProductName"});
                table57.AddRow(new string[] {
                            "Today",
                            "1",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "1000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table57.AddRow(new string[] {
                            "Today",
                            "2",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "500.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table57.AddRow(new string[] {
                            "Today",
                            "3",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "2500.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table57.AddRow(new string[] {
                            "Today",
                            "4",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "1500.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table57.AddRow(new string[] {
                            "Today",
                            "5",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "300.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table57.AddRow(new string[] {
                            "Today",
                            "6",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "4000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table57.AddRow(new string[] {
                            "Today",
                            "7",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "6000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table57.AddRow(new string[] {
                            "Today",
                            "8",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "10000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table57.AddRow(new string[] {
                            "Today",
                            "1",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "1000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table57.AddRow(new string[] {
                            "Today",
                            "2",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "500.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table57.AddRow(new string[] {
                            "Today",
                            "3",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "2500.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table57.AddRow(new string[] {
                            "Today",
                            "4",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "1500.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table57.AddRow(new string[] {
                            "Today",
                            "1",
                            "Sale",
                            "Test Merchant 3",
                            "123456782",
                            "Test Estate 2",
                            "Safaricom",
                            "10000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
#line 72
 testRunner.When("I perform the following transactions", ((string)(null)), table57, "When ");
#line hidden
                TechTalk.SpecFlow.Table table58 = new TechTalk.SpecFlow.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "TransactionNumber",
                            "ResponseCode",
                            "ResponseMessage"});
                table58.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "1",
                            "0000",
                            "SUCCESS"});
                table58.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "2",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table58.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "3",
                            "0000",
                            "SUCCESS"});
                table58.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "4",
                            "0000",
                            "SUCCESS"});
                table58.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "5",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table58.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "6",
                            "0000",
                            "SUCCESS"});
                table58.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "7",
                            "0000",
                            "SUCCESS"});
                table58.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "8",
                            "0000",
                            "SUCCESS"});
                table58.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "1",
                            "0000",
                            "SUCCESS"});
                table58.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "2",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table58.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "3",
                            "0000",
                            "SUCCESS"});
                table58.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "4",
                            "0000",
                            "SUCCESS"});
                table58.AddRow(new string[] {
                            "Test Estate 2",
                            "Test Merchant 3",
                            "1",
                            "0000",
                            "SUCCESS"});
#line 90
 testRunner.Then("transaction response should contain the following information", ((string)(null)), table58, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table59 = new TechTalk.SpecFlow.Table(new string[] {
                            "WeekNumber",
                            "Year",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table59.AddRow(new string[] {
                            "42",
                            "2020",
                            "9",
                            "30000.00"});
#line 108
 testRunner.When("I get the Estate Transactions By Week Report for Estate \'Test Estate 1\' with the " +
                        "Start Date \'Today\' and the End Date \'Today\' the following data is returned", ((string)(null)), table59, "When ");
#line hidden
                TechTalk.SpecFlow.Table table60 = new TechTalk.SpecFlow.Table(new string[] {
                            "WeekNumber",
                            "Year",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table60.AddRow(new string[] {
                            "42",
                            "2020",
                            "1",
                            "10000.00"});
#line 112
 testRunner.When("I get the Estate Transactions By Week Report for Estate \'Test Estate 2\' with the " +
                        "Start Date \'Today\' and the End Date \'Today\' the following data is returned", ((string)(null)), table60, "When ");
#line hidden
                TechTalk.SpecFlow.Table table61 = new TechTalk.SpecFlow.Table(new string[] {
                            "WeekNumber",
                            "Year",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table61.AddRow(new string[] {
                            "42",
                            "2020",
                            "3",
                            "5000.00"});
#line 116
 testRunner.When("I get the Merchant Transactions By Week Report for Estate \'Test Estate 1\' and Mer" +
                        "chant \'Test Merchant 2\' with the Start Date \'Today\' and the End Date \'Today\' the" +
                        " following data is returned", ((string)(null)), table61, "When ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Sales Transactions By Week - Transactions On Mutiple Days")]
        [Xunit.TraitAttribute("FeatureTitle", "TransactionsByWeekReports")]
        [Xunit.TraitAttribute("Description", "Sales Transactions By Week - Transactions On Mutiple Days")]
        [Xunit.TraitAttribute("Category", "PRTest")]
        public virtual void SalesTransactionsByWeek_TransactionsOnMutipleDays()
        {
            string[] tagsOfScenario = new string[] {
                    "PRTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sales Transactions By Week - Transactions On Mutiple Days", null, tagsOfScenario, argumentsOfScenario);
#line 121
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 123
 testRunner.Given("I set the date for today to \"15/10/2020\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table62 = new TechTalk.SpecFlow.Table(new string[] {
                            "DateTime",
                            "TransactionNumber",
                            "TransactionType",
                            "MerchantName",
                            "DeviceIdentifier",
                            "EstateName",
                            "OperatorName",
                            "TransactionAmount",
                            "CustomerAccountNumber",
                            "CustomerEmailAddress",
                            "ContractDescription",
                            "ProductName"});
                table62.AddRow(new string[] {
                            "LastMonth",
                            "1",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "1000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "LastWeek",
                            "2",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "500.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "LastWeek",
                            "3",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "2500.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "Yesterday",
                            "4",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "1500.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "Yesterday",
                            "5",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "300.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "Today",
                            "6",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "4000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "Today",
                            "7",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "6000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "Today",
                            "8",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "10000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "Today",
                            "1",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "1000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "Today",
                            "2",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "500.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "Today",
                            "3",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "2500.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "Today",
                            "4",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "1500.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "LastMonth",
                            "1",
                            "Sale",
                            "Test Merchant 3",
                            "123456782",
                            "Test Estate 2",
                            "Safaricom",
                            "1000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "LastWeek",
                            "2",
                            "Sale",
                            "Test Merchant 3",
                            "123456782",
                            "Test Estate 2",
                            "Safaricom",
                            "2000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "Yesterday",
                            "3",
                            "Sale",
                            "Test Merchant 3",
                            "123456782",
                            "Test Estate 2",
                            "Safaricom",
                            "1000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table62.AddRow(new string[] {
                            "Today",
                            "4",
                            "Sale",
                            "Test Merchant 3",
                            "123456782",
                            "Test Estate 2",
                            "Safaricom",
                            "1000.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
#line 125
 testRunner.When("I perform the following transactions", ((string)(null)), table62, "When ");
#line hidden
                TechTalk.SpecFlow.Table table63 = new TechTalk.SpecFlow.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "TransactionNumber",
                            "ResponseCode",
                            "ResponseMessage"});
                table63.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "1",
                            "0000",
                            "SUCCESS"});
                table63.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "2",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table63.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "3",
                            "0000",
                            "SUCCESS"});
                table63.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "4",
                            "0000",
                            "SUCCESS"});
                table63.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "5",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table63.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "6",
                            "0000",
                            "SUCCESS"});
                table63.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "7",
                            "0000",
                            "SUCCESS"});
                table63.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "8",
                            "0000",
                            "SUCCESS"});
                table63.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "1",
                            "0000",
                            "SUCCESS"});
                table63.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "2",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table63.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "3",
                            "0000",
                            "SUCCESS"});
                table63.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "4",
                            "0000",
                            "SUCCESS"});
                table63.AddRow(new string[] {
                            "Test Estate 2",
                            "Test Merchant 3",
                            "1",
                            "0000",
                            "SUCCESS"});
                table63.AddRow(new string[] {
                            "Test Estate 2",
                            "Test Merchant 3",
                            "2",
                            "0000",
                            "SUCCESS"});
                table63.AddRow(new string[] {
                            "Test Estate 2",
                            "Test Merchant 3",
                            "3",
                            "0000",
                            "SUCCESS"});
                table63.AddRow(new string[] {
                            "Test Estate 2",
                            "Test Merchant 3",
                            "4",
                            "0000",
                            "SUCCESS"});
#line 146
 testRunner.Then("transaction response should contain the following information", ((string)(null)), table63, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table64 = new TechTalk.SpecFlow.Table(new string[] {
                            "WeekNumber",
                            "Year",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table64.AddRow(new string[] {
                            "42",
                            "2020",
                            "7",
                            "26500.00"});
                table64.AddRow(new string[] {
                            "41",
                            "2020",
                            "1",
                            "2500.00"});
                table64.AddRow(new string[] {
                            "38",
                            "2020",
                            "1",
                            "1000.00"});
#line 167
 testRunner.When("I get the Estate Transactions By Week Report for Estate \'Test Estate 1\' with the " +
                        "Start Date \'LastMonth\' and the End Date \'Today\' the following data is returned", ((string)(null)), table64, "When ");
#line hidden
                TechTalk.SpecFlow.Table table65 = new TechTalk.SpecFlow.Table(new string[] {
                            "WeekNumber",
                            "Year",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table65.AddRow(new string[] {
                            "42",
                            "2020",
                            "2",
                            "2000.00"});
                table65.AddRow(new string[] {
                            "41",
                            "2020",
                            "1",
                            "2000.00"});
                table65.AddRow(new string[] {
                            "38",
                            "2020",
                            "1",
                            "1000.00"});
#line 173
 testRunner.When("I get the Estate Transactions By Week Report for Estate \'Test Estate 2\' with the " +
                        "Start Date \'LastMonth\' and the End Date \'Today\' the following data is returned", ((string)(null)), table65, "When ");
#line hidden
                TechTalk.SpecFlow.Table table66 = new TechTalk.SpecFlow.Table(new string[] {
                            "WeekNumber",
                            "Year",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table66.AddRow(new string[] {
                            "42",
                            "2020",
                            "3",
                            "5000.00"});
#line 179
 testRunner.When("I get the Merchant Transactions By Week Report for Estate \'Test Estate 1\' and Mer" +
                        "chant \'Test Merchant 2\' with the Start Date \'LastMonth\' and the End Date \'Today\'" +
                        " the following data is returned", ((string)(null)), table66, "When ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TransactionsByWeekReportsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TransactionsByWeekReportsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
