// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.5.0.0
//      SpecFlow Generator Version:3.5.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EstateReporting.IntegrationTests.Reporting
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "base")]
    [Xunit.TraitAttribute("Category", "shared")]
    public partial class TransactionsByMerchantReportsFeature : object, Xunit.IClassFixture<TransactionsByMerchantReportsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "base",
                "shared"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TransactionsByMerchantReports.feature"
#line hidden
        
        public TransactionsByMerchantReportsFeature(TransactionsByMerchantReportsFeature.FixtureData fixtureData, EstateReporting_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Reporting", "TransactionsByMerchantReports", null, ProgrammingLanguage.CSharp, new string[] {
                        "base",
                        "shared"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Description"});
            table24.AddRow(new string[] {
                        "estateManagement",
                        "Estate Managememt REST Scope",
                        "A scope for Estate Managememt REST"});
            table24.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST  Scope",
                        "A scope for Transaction Processor REST"});
#line 6
 testRunner.Given("I create the following api scopes", ((string)(null)), table24, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "ResourceName",
                        "DisplayName",
                        "Secret",
                        "Scopes",
                        "UserClaims"});
            table25.AddRow(new string[] {
                        "estateManagement",
                        "Estate Managememt REST",
                        "Secret1",
                        "estateManagement",
                        "MerchantId, EstateId, role"});
            table25.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST",
                        "Secret1",
                        "transactionProcessor",
                        ""});
#line 11
 testRunner.Given("the following api resources exist", ((string)(null)), table25, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "ClientId",
                        "ClientName",
                        "Secret",
                        "AllowedScopes",
                        "AllowedGrantTypes"});
            table26.AddRow(new string[] {
                        "serviceClient",
                        "Service Client",
                        "Secret1",
                        "estateManagement,transactionProcessor",
                        "client_credentials"});
#line 16
 testRunner.Given("the following clients exist", ((string)(null)), table26, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "ClientId"});
            table27.AddRow(new string[] {
                        "serviceClient"});
#line 20
 testRunner.Given("I have a token to access the estate management and transaction processor resource" +
                    "s", ((string)(null)), table27, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName"});
            table28.AddRow(new string[] {
                        "Test Estate 1"});
            table28.AddRow(new string[] {
                        "Test Estate 2"});
#line 24
 testRunner.Given("I have created the following estates", ((string)(null)), table28, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "RequireCustomMerchantNumber",
                        "RequireCustomTerminalNumber"});
            table29.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "True",
                        "True"});
            table29.AddRow(new string[] {
                        "Test Estate 2",
                        "Safaricom",
                        "True",
                        "True"});
#line 29
 testRunner.Given("I have created the following operators", ((string)(null)), table29, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription"});
            table30.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract"});
            table30.AddRow(new string[] {
                        "Test Estate 2",
                        "Safaricom",
                        "Safaricom Contract"});
#line 34
 testRunner.Given("I create a contract with the following values", ((string)(null)), table30, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription",
                        "ProductName",
                        "DisplayText",
                        "Value"});
            table31.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Custom",
                        ""});
            table31.AddRow(new string[] {
                        "Test Estate 2",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Custom",
                        ""});
#line 39
 testRunner.When("I create the following Products", ((string)(null)), table31, "When ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription",
                        "ProductName",
                        "CalculationType",
                        "FeeDescription",
                        "Value"});
            table32.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Fixed",
                        "Merchant Commission",
                        "2.50"});
            table32.AddRow(new string[] {
                        "Test Estate 2",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Percentage",
                        "Merchant Commission",
                        "0.85"});
#line 44
 testRunner.When("I add the following Transaction Fees", ((string)(null)), table32, "When ");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "MerchantName",
                        "AddressLine1",
                        "Town",
                        "Region",
                        "Country",
                        "ContactName",
                        "EmailAddress",
                        "EstateName"});
            table33.AddRow(new string[] {
                        "Test Merchant 1",
                        "Address Line 1",
                        "TestTown",
                        "Test Region",
                        "United Kingdom",
                        "Test Contact 1",
                        "testcontact1@merchant1.co.uk",
                        "Test Estate 1"});
            table33.AddRow(new string[] {
                        "Test Merchant 2",
                        "Address Line 1",
                        "TestTown",
                        "Test Region",
                        "United Kingdom",
                        "Test Contact 2",
                        "testcontact2@merchant2.co.uk",
                        "Test Estate 1"});
            table33.AddRow(new string[] {
                        "Test Merchant 3",
                        "Address Line 1",
                        "TestTown",
                        "Test Region",
                        "United Kingdom",
                        "Test Contact 3",
                        "testcontact3@merchant2.co.uk",
                        "Test Estate 2"});
#line 49
 testRunner.Given("I create the following merchants", ((string)(null)), table33, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperatorName",
                        "MerchantName",
                        "MerchantNumber",
                        "TerminalNumber",
                        "EstateName"});
            table34.AddRow(new string[] {
                        "Safaricom",
                        "Test Merchant 1",
                        "00000001",
                        "10000001",
                        "Test Estate 1"});
            table34.AddRow(new string[] {
                        "Safaricom",
                        "Test Merchant 2",
                        "00000002",
                        "10000002",
                        "Test Estate 1"});
            table34.AddRow(new string[] {
                        "Safaricom",
                        "Test Merchant 3",
                        "00000003",
                        "10000003",
                        "Test Estate 2"});
#line 55
 testRunner.Given("I have assigned the following  operator to the merchants", ((string)(null)), table34, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "DeviceIdentifier",
                        "MerchantName",
                        "EstateName"});
            table35.AddRow(new string[] {
                        "123456780",
                        "Test Merchant 1",
                        "Test Estate 1"});
            table35.AddRow(new string[] {
                        "123456781",
                        "Test Merchant 2",
                        "Test Estate 1"});
            table35.AddRow(new string[] {
                        "123456782",
                        "Test Merchant 3",
                        "Test Estate 2"});
#line 61
 testRunner.Given("I have assigned the following devices to the merchants", ((string)(null)), table35, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "Reference",
                        "Amount",
                        "DateTime",
                        "MerchantName",
                        "EstateName"});
            table36.AddRow(new string[] {
                        "Deposit1",
                        "3000.00",
                        "Today",
                        "Test Merchant 1",
                        "Test Estate 1"});
            table36.AddRow(new string[] {
                        "Deposit1",
                        "1000.00",
                        "Today",
                        "Test Merchant 2",
                        "Test Estate 1"});
            table36.AddRow(new string[] {
                        "Deposit1",
                        "1000.00",
                        "Today",
                        "Test Merchant 3",
                        "Test Estate 2"});
#line 67
 testRunner.Given("I make the following manual merchant deposits", ((string)(null)), table36, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Sales Transactions By Merchant - Transactions All For Same Merchant")]
        [Xunit.TraitAttribute("FeatureTitle", "TransactionsByMerchantReports")]
        [Xunit.TraitAttribute("Description", "Sales Transactions By Merchant - Transactions All For Same Merchant")]
        public virtual void SalesTransactionsByMerchant_TransactionsAllForSameMerchant()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sales Transactions By Merchant - Transactions All For Same Merchant", null, tagsOfScenario, argumentsOfScenario);
#line 73
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                            "DateTime",
                            "TransactionNumber",
                            "TransactionType",
                            "MerchantName",
                            "DeviceIdentifier",
                            "EstateName",
                            "OperatorName",
                            "TransactionAmount",
                            "CustomerAccountNumber",
                            "CustomerEmailAddress",
                            "ContractDescription",
                            "ProductName"});
                table37.AddRow(new string[] {
                            "LastMonth",
                            "1",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "10.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table37.AddRow(new string[] {
                            "LastWeek",
                            "2",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "5.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table37.AddRow(new string[] {
                            "LastWeek",
                            "3",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "25.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table37.AddRow(new string[] {
                            "Yesterday",
                            "4",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "15.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table37.AddRow(new string[] {
                            "Yesterday",
                            "5",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "3.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table37.AddRow(new string[] {
                            "Today",
                            "6",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "40.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table37.AddRow(new string[] {
                            "Today",
                            "7",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "60.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table37.AddRow(new string[] {
                            "Today",
                            "8",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
#line 74
 testRunner.When("I perform the following transactions", ((string)(null)), table37, "When ");
#line hidden
                TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "TransactionNumber",
                            "ResponseCode",
                            "ResponseMessage"});
                table38.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "1",
                            "0000",
                            "SUCCESS"});
                table38.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "2",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table38.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "3",
                            "0000",
                            "SUCCESS"});
                table38.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "4",
                            "0000",
                            "SUCCESS"});
                table38.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "5",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table38.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "6",
                            "0000",
                            "SUCCESS"});
                table38.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "7",
                            "0000",
                            "SUCCESS"});
                table38.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "8",
                            "0000",
                            "SUCCESS"});
#line 85
 testRunner.Then("transaction response should contain the following information", ((string)(null)), table38, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                            "MerchantName",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table39.AddRow(new string[] {
                            "Test Merchant 1",
                            "3",
                            "200.00"});
#line 97
 testRunner.When("I get the Estate Transactions By Merchant Report for Estate \'Test Estate 1\' with " +
                        "the Start Date \'Today\' and the End Date \'Today\' the following data is returned", ((string)(null)), table39, "When ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Sales Transactions By Merchant - Transactions For Mutiple Merchants")]
        [Xunit.TraitAttribute("FeatureTitle", "TransactionsByMerchantReports")]
        [Xunit.TraitAttribute("Description", "Sales Transactions By Merchant - Transactions For Mutiple Merchants")]
        public virtual void SalesTransactionsByMerchant_TransactionsForMutipleMerchants()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sales Transactions By Merchant - Transactions For Mutiple Merchants", null, tagsOfScenario, argumentsOfScenario);
#line 102
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                            "DateTime",
                            "TransactionNumber",
                            "TransactionType",
                            "MerchantName",
                            "DeviceIdentifier",
                            "EstateName",
                            "OperatorName",
                            "TransactionAmount",
                            "CustomerAccountNumber",
                            "CustomerEmailAddress",
                            "ContractDescription",
                            "ProductName"});
                table40.AddRow(new string[] {
                            "LastMonth",
                            "1",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "10.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "LastWeek",
                            "2",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "5.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "LastWeek",
                            "3",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "25.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "Yesterday",
                            "4",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "15.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "Yesterday",
                            "5",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "3.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "Today",
                            "6",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "40.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "Today",
                            "7",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "60.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "Today",
                            "8",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "Today",
                            "1",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "Today",
                            "2",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "5.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "Today",
                            "3",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "25.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "Today",
                            "4",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "150.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "LastMonth",
                            "1",
                            "Sale",
                            "Test Merchant 3",
                            "123456782",
                            "Test Estate 2",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "LastWeek",
                            "2",
                            "Sale",
                            "Test Merchant 3",
                            "123456782",
                            "Test Estate 2",
                            "Safaricom",
                            "200.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "Yesterday",
                            "3",
                            "Sale",
                            "Test Merchant 3",
                            "123456782",
                            "Test Estate 2",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table40.AddRow(new string[] {
                            "Today",
                            "4",
                            "Sale",
                            "Test Merchant 3",
                            "123456782",
                            "Test Estate 2",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
#line 103
 testRunner.When("I perform the following transactions", ((string)(null)), table40, "When ");
#line hidden
                TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "TransactionNumber",
                            "ResponseCode",
                            "ResponseMessage"});
                table41.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "1",
                            "0000",
                            "SUCCESS"});
                table41.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "2",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table41.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "3",
                            "0000",
                            "SUCCESS"});
                table41.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "4",
                            "0000",
                            "SUCCESS"});
                table41.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "5",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table41.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "6",
                            "0000",
                            "SUCCESS"});
                table41.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "7",
                            "0000",
                            "SUCCESS"});
                table41.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "8",
                            "0000",
                            "SUCCESS"});
                table41.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "1",
                            "0000",
                            "SUCCESS"});
                table41.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "2",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table41.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "3",
                            "0000",
                            "SUCCESS"});
                table41.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "4",
                            "0000",
                            "SUCCESS"});
                table41.AddRow(new string[] {
                            "Test Estate 2",
                            "Test Merchant 3",
                            "1",
                            "0000",
                            "SUCCESS"});
                table41.AddRow(new string[] {
                            "Test Estate 2",
                            "Test Merchant 3",
                            "2",
                            "0000",
                            "SUCCESS"});
                table41.AddRow(new string[] {
                            "Test Estate 2",
                            "Test Merchant 3",
                            "3",
                            "0000",
                            "SUCCESS"});
                table41.AddRow(new string[] {
                            "Test Estate 2",
                            "Test Merchant 3",
                            "4",
                            "0000",
                            "SUCCESS"});
#line 124
 testRunner.Then("transaction response should contain the following information", ((string)(null)), table41, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                            "MerchantName",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table42.AddRow(new string[] {
                            "Test Merchant 1",
                            "6",
                            "250.00"});
                table42.AddRow(new string[] {
                            "Test Merchant 2",
                            "3",
                            "275.00"});
#line 145
 testRunner.When("I get the Estate Transactions By Merchant Report for Estate \'Test Estate 1\' with " +
                        "the Start Date \'LastMonth\' and the End Date \'Today\' the following data is return" +
                        "ed", ((string)(null)), table42, "When ");
#line hidden
                TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                            "MerchantName",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table43.AddRow(new string[] {
                            "Test Merchant 3",
                            "4",
                            "500.00"});
#line 150
 testRunner.When("I get the Estate Transactions By Merchant Report for Estate \'Test Estate 2\' with " +
                        "the Start Date \'LastMonth\' and the End Date \'Today\' the following data is return" +
                        "ed", ((string)(null)), table43, "When ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TransactionsByMerchantReportsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TransactionsByMerchantReportsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
