// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.5.0.0
//      SpecFlow Generator Version:3.5.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EstateReporting.IntegrationTests.Reporting
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "base")]
    [Xunit.TraitAttribute("Category", "shared")]
    public partial class TransactionsByDayReportsFeature : object, Xunit.IClassFixture<TransactionsByDayReportsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "base",
                "shared"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TransactionsByDayReports.feature"
#line hidden
        
        public TransactionsByDayReportsFeature(TransactionsByDayReportsFeature.FixtureData fixtureData, EstateReporting_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Reporting", "TransactionsByDayReports", null, ProgrammingLanguage.CSharp, new string[] {
                        "base",
                        "shared"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "ResourceName",
                        "DisplayName",
                        "Secret",
                        "Scopes",
                        "UserClaims"});
            table1.AddRow(new string[] {
                        "estateManagement",
                        "Estate Managememt REST",
                        "Secret1",
                        "estateManagement",
                        "MerchantId, EstateId, role"});
            table1.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST",
                        "Secret1",
                        "transactionProcessor",
                        ""});
#line 6
 testRunner.Given("the following api resources exist", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "ClientId",
                        "ClientName",
                        "Secret",
                        "AllowedScopes",
                        "AllowedGrantTypes"});
            table2.AddRow(new string[] {
                        "serviceClient",
                        "Service Client",
                        "Secret1",
                        "estateManagement,transactionProcessor",
                        "client_credentials"});
#line 11
 testRunner.Given("the following clients exist", ((string)(null)), table2, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "ClientId"});
            table3.AddRow(new string[] {
                        "serviceClient"});
#line 15
 testRunner.Given("I have a token to access the estate management and transaction processor resource" +
                    "s", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName"});
            table4.AddRow(new string[] {
                        "Test Estate 1"});
            table4.AddRow(new string[] {
                        "Test Estate 2"});
#line 19
 testRunner.Given("I have created the following estates", ((string)(null)), table4, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "RequireCustomMerchantNumber",
                        "RequireCustomTerminalNumber"});
            table5.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "True",
                        "True"});
            table5.AddRow(new string[] {
                        "Test Estate 2",
                        "Safaricom",
                        "True",
                        "True"});
#line 24
 testRunner.Given("I have created the following operators", ((string)(null)), table5, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription"});
            table6.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract"});
            table6.AddRow(new string[] {
                        "Test Estate 2",
                        "Safaricom",
                        "Safaricom Contract"});
#line 29
 testRunner.Given("I create a contract with the following values", ((string)(null)), table6, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription",
                        "ProductName",
                        "DisplayText",
                        "Value"});
            table7.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Custom",
                        ""});
            table7.AddRow(new string[] {
                        "Test Estate 2",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Custom",
                        ""});
#line 34
 testRunner.When("I create the following Products", ((string)(null)), table7, "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription",
                        "ProductName",
                        "CalculationType",
                        "FeeDescription",
                        "Value"});
            table8.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Fixed",
                        "Merchant Commission",
                        "2.50"});
            table8.AddRow(new string[] {
                        "Test Estate 2",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Percentage",
                        "Merchant Commission",
                        "0.85"});
#line 39
 testRunner.When("I add the following Transaction Fees", ((string)(null)), table8, "When ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "MerchantName",
                        "AddressLine1",
                        "Town",
                        "Region",
                        "Country",
                        "ContactName",
                        "EmailAddress",
                        "EstateName"});
            table9.AddRow(new string[] {
                        "Test Merchant 1",
                        "Address Line 1",
                        "TestTown",
                        "Test Region",
                        "United Kingdom",
                        "Test Contact 1",
                        "testcontact1@merchant1.co.uk",
                        "Test Estate 1"});
            table9.AddRow(new string[] {
                        "Test Merchant 2",
                        "Address Line 1",
                        "TestTown",
                        "Test Region",
                        "United Kingdom",
                        "Test Contact 2",
                        "testcontact2@merchant2.co.uk",
                        "Test Estate 1"});
            table9.AddRow(new string[] {
                        "Test Merchant 3",
                        "Address Line 1",
                        "TestTown",
                        "Test Region",
                        "United Kingdom",
                        "Test Contact 3",
                        "testcontact3@merchant2.co.uk",
                        "Test Estate 2"});
#line 44
 testRunner.Given("I create the following merchants", ((string)(null)), table9, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperatorName",
                        "MerchantName",
                        "MerchantNumber",
                        "TerminalNumber",
                        "EstateName"});
            table10.AddRow(new string[] {
                        "Safaricom",
                        "Test Merchant 1",
                        "00000001",
                        "10000001",
                        "Test Estate 1"});
            table10.AddRow(new string[] {
                        "Safaricom",
                        "Test Merchant 2",
                        "00000002",
                        "10000002",
                        "Test Estate 1"});
            table10.AddRow(new string[] {
                        "Safaricom",
                        "Test Merchant 3",
                        "00000003",
                        "10000003",
                        "Test Estate 2"});
#line 50
 testRunner.Given("I have assigned the following  operator to the merchants", ((string)(null)), table10, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "DeviceIdentifier",
                        "MerchantName",
                        "EstateName"});
            table11.AddRow(new string[] {
                        "123456780",
                        "Test Merchant 1",
                        "Test Estate 1"});
            table11.AddRow(new string[] {
                        "123456781",
                        "Test Merchant 2",
                        "Test Estate 1"});
            table11.AddRow(new string[] {
                        "123456782",
                        "Test Merchant 3",
                        "Test Estate 2"});
#line 56
 testRunner.Given("I have assigned the following devices to the merchants", ((string)(null)), table11, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Reference",
                        "Amount",
                        "DateTime",
                        "MerchantName",
                        "EstateName"});
            table12.AddRow(new string[] {
                        "Deposit1",
                        "3000.00",
                        "Today",
                        "Test Merchant 1",
                        "Test Estate 1"});
            table12.AddRow(new string[] {
                        "Deposit1",
                        "1000.00",
                        "Today",
                        "Test Merchant 2",
                        "Test Estate 1"});
            table12.AddRow(new string[] {
                        "Deposit1",
                        "1000.00",
                        "Today",
                        "Test Merchant 3",
                        "Test Estate 2"});
#line 62
 testRunner.Given("I make the following manual merchant deposits", ((string)(null)), table12, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Sales Transactions By Day - Transactions All On Same Day")]
        [Xunit.TraitAttribute("FeatureTitle", "TransactionsByDayReports")]
        [Xunit.TraitAttribute("Description", "Sales Transactions By Day - Transactions All On Same Day")]
        public virtual void SalesTransactionsByDay_TransactionsAllOnSameDay()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sales Transactions By Day - Transactions All On Same Day", null, tagsOfScenario, argumentsOfScenario);
#line 68
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "DateTime",
                            "TransactionNumber",
                            "TransactionType",
                            "MerchantName",
                            "DeviceIdentifier",
                            "EstateName",
                            "OperatorName",
                            "TransactionAmount",
                            "CustomerAccountNumber",
                            "CustomerEmailAddress",
                            "ContractDescription",
                            "ProductName"});
                table13.AddRow(new string[] {
                            "Today",
                            "1",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table13.AddRow(new string[] {
                            "Today",
                            "2",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "5.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table13.AddRow(new string[] {
                            "Today",
                            "3",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "25.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table13.AddRow(new string[] {
                            "Today",
                            "4",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "150.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table13.AddRow(new string[] {
                            "Today",
                            "5",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "3.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table13.AddRow(new string[] {
                            "Today",
                            "6",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "40.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table13.AddRow(new string[] {
                            "Today",
                            "7",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "60.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table13.AddRow(new string[] {
                            "Today",
                            "8",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table13.AddRow(new string[] {
                            "Today",
                            "1",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table13.AddRow(new string[] {
                            "Today",
                            "2",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "5.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table13.AddRow(new string[] {
                            "Today",
                            "3",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "25.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table13.AddRow(new string[] {
                            "Today",
                            "4",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "15.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table13.AddRow(new string[] {
                            "Today",
                            "1",
                            "Sale",
                            "Test Merchant 3",
                            "123456782",
                            "Test Estate 2",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
#line 69
 testRunner.When("I perform the following transactions", ((string)(null)), table13, "When ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "TransactionNumber",
                            "ResponseCode",
                            "ResponseMessage"});
                table14.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "1",
                            "0000",
                            "SUCCESS"});
                table14.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "2",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table14.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "3",
                            "0000",
                            "SUCCESS"});
                table14.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "4",
                            "0000",
                            "SUCCESS"});
                table14.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "5",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table14.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "6",
                            "0000",
                            "SUCCESS"});
                table14.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "7",
                            "0000",
                            "SUCCESS"});
                table14.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "8",
                            "0000",
                            "SUCCESS"});
                table14.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "1",
                            "0000",
                            "SUCCESS"});
                table14.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "2",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table14.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "3",
                            "0000",
                            "SUCCESS"});
                table14.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "4",
                            "0000",
                            "SUCCESS"});
                table14.AddRow(new string[] {
                            "Test Estate 2",
                            "Test Merchant 3",
                            "1",
                            "0000",
                            "SUCCESS"});
#line 87
 testRunner.Then("transaction response should contain the following information", ((string)(null)), table14, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "Date",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table15.AddRow(new string[] {
                            "Today",
                            "9",
                            "615.00"});
#line 105
 testRunner.When("I get the Estate Transactions By Date Report for Estate \'Test Estate 1\' with the " +
                        "Start Date \'Today\' and the End Date \'Today\' the following data is returned", ((string)(null)), table15, "When ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "Date",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table16.AddRow(new string[] {
                            "Today",
                            "1",
                            "100.00"});
#line 109
 testRunner.When("I get the Estate Transactions By Date Report for Estate \'Test Estate 2\' with the " +
                        "Start Date \'Today\' and the End Date \'Today\' the following data is returned", ((string)(null)), table16, "When ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "Date",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table17.AddRow(new string[] {
                            "Today",
                            "3",
                            "140.00"});
#line 113
 testRunner.When("I get the Merchant Transactions By Date Report for Estate \'Test Estate 1\' and Mer" +
                        "chant \'Test Merchant 2\' with the Start Date \'Today\' and the End Date \'Today\' the" +
                        " following data is returned", ((string)(null)), table17, "When ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Sales Transactions By Day - Transactions On Mutiple Days")]
        [Xunit.TraitAttribute("FeatureTitle", "TransactionsByDayReports")]
        [Xunit.TraitAttribute("Description", "Sales Transactions By Day - Transactions On Mutiple Days")]
        [Xunit.TraitAttribute("Category", "PRTest")]
        public virtual void SalesTransactionsByDay_TransactionsOnMutipleDays()
        {
            string[] tagsOfScenario = new string[] {
                    "PRTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sales Transactions By Day - Transactions On Mutiple Days", null, tagsOfScenario, argumentsOfScenario);
#line 118
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "DateTime",
                            "TransactionNumber",
                            "TransactionType",
                            "MerchantName",
                            "DeviceIdentifier",
                            "EstateName",
                            "OperatorName",
                            "TransactionAmount",
                            "CustomerAccountNumber",
                            "CustomerEmailAddress",
                            "ContractDescription",
                            "ProductName"});
                table18.AddRow(new string[] {
                            "LastMonth",
                            "1",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "10.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "LastWeek",
                            "2",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "5.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "LastWeek",
                            "3",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "25.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "Yesterday",
                            "4",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "15.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "Yesterday",
                            "5",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "3.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "Today",
                            "6",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "40.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "Today",
                            "7",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "60.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "Today",
                            "8",
                            "Sale",
                            "Test Merchant 1",
                            "123456780",
                            "Test Estate 1",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "Today",
                            "1",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "Today",
                            "2",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "5.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "Today",
                            "3",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "25.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "Today",
                            "4",
                            "Sale",
                            "Test Merchant 2",
                            "123456781",
                            "Test Estate 1",
                            "Safaricom",
                            "150.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "LastMonth",
                            "1",
                            "Sale",
                            "Test Merchant 3",
                            "123456782",
                            "Test Estate 2",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "LastWeek",
                            "2",
                            "Sale",
                            "Test Merchant 3",
                            "123456782",
                            "Test Estate 2",
                            "Safaricom",
                            "200.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "Yesterday",
                            "3",
                            "Sale",
                            "Test Merchant 3",
                            "123456782",
                            "Test Estate 2",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
                table18.AddRow(new string[] {
                            "Today",
                            "4",
                            "Sale",
                            "Test Merchant 3",
                            "123456782",
                            "Test Estate 2",
                            "Safaricom",
                            "100.00",
                            "123456789",
                            "",
                            "Safaricom Contract",
                            "Variable Topup"});
#line 119
 testRunner.When("I perform the following transactions", ((string)(null)), table18, "When ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "EstateName",
                            "MerchantName",
                            "TransactionNumber",
                            "ResponseCode",
                            "ResponseMessage"});
                table19.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "1",
                            "0000",
                            "SUCCESS"});
                table19.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "2",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table19.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "3",
                            "0000",
                            "SUCCESS"});
                table19.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "4",
                            "0000",
                            "SUCCESS"});
                table19.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "5",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table19.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "6",
                            "0000",
                            "SUCCESS"});
                table19.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "7",
                            "0000",
                            "SUCCESS"});
                table19.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 1",
                            "8",
                            "0000",
                            "SUCCESS"});
                table19.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "1",
                            "0000",
                            "SUCCESS"});
                table19.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "2",
                            "1008",
                            "DECLINED BY OPERATOR"});
                table19.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "3",
                            "0000",
                            "SUCCESS"});
                table19.AddRow(new string[] {
                            "Test Estate 1",
                            "Test Merchant 2",
                            "4",
                            "0000",
                            "SUCCESS"});
                table19.AddRow(new string[] {
                            "Test Estate 2",
                            "Test Merchant 3",
                            "1",
                            "0000",
                            "SUCCESS"});
                table19.AddRow(new string[] {
                            "Test Estate 2",
                            "Test Merchant 3",
                            "2",
                            "0000",
                            "SUCCESS"});
                table19.AddRow(new string[] {
                            "Test Estate 2",
                            "Test Merchant 3",
                            "3",
                            "0000",
                            "SUCCESS"});
                table19.AddRow(new string[] {
                            "Test Estate 2",
                            "Test Merchant 3",
                            "4",
                            "0000",
                            "SUCCESS"});
#line 140
 testRunner.Then("transaction response should contain the following information", ((string)(null)), table19, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "Date",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table20.AddRow(new string[] {
                            "Today",
                            "6",
                            "475.00"});
                table20.AddRow(new string[] {
                            "Yesterday",
                            "1",
                            "15.00"});
                table20.AddRow(new string[] {
                            "LastWeek",
                            "1",
                            "25.00"});
                table20.AddRow(new string[] {
                            "LastMonth",
                            "1",
                            "10.00"});
#line 161
 testRunner.When("I get the Estate Transactions By Date Report for Estate \'Test Estate 1\' with the " +
                        "Start Date \'LastMonth\' and the End Date \'Today\' the following data is returned", ((string)(null)), table20, "When ");
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "Date",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table21.AddRow(new string[] {
                            "Today",
                            "1",
                            "100.00"});
                table21.AddRow(new string[] {
                            "Yesterday",
                            "1",
                            "100.00"});
                table21.AddRow(new string[] {
                            "LastWeek",
                            "1",
                            "200.00"});
                table21.AddRow(new string[] {
                            "LastMonth",
                            "1",
                            "100.00"});
#line 168
 testRunner.When("I get the Estate Transactions By Date Report for Estate \'Test Estate 2\' with the " +
                        "Start Date \'LastMonth\' and the End Date \'Today\' the following data is returned", ((string)(null)), table21, "When ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "Date",
                            "NumberOfTransactions",
                            "ValueOfTransactions"});
                table22.AddRow(new string[] {
                            "Today",
                            "3",
                            "275.00"});
#line 175
 testRunner.When("I get the Merchant Transactions By Date Report for Estate \'Test Estate 1\' and Mer" +
                        "chant \'Test Merchant 2\' with the Start Date \'LastMonth\' and the End Date \'Today\'" +
                        " the following data is returned", ((string)(null)), table22, "When ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TransactionsByDayReportsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TransactionsByDayReportsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
